### ISSUE TITLE
Does not display Thumbnail consistantly

### ISSUE THREAD

**Issue by BradleyDB** [cyrillbolliger/conditional-featured-image#1]
On Grid View pages (where child page thumbnails are shown), thumbnails do now show up if the Grid View page has a parent page. Grid View pages that are a top level page display thumbnails.
Edit: Theme is Prosperity by Themes Harbor

**Comment by cyrillbolliger** [comment]
Which pluings and theme are you using? Please consider the important note:
> If your theme does a customized call to load the featured image (like the Twenty Seventeen theme), this plugin might not work! Use `get_the_post_thumbnail()` or `wp_get_attachment_image()` to be sure it works.

**Comment by cyrillbolliger** [comment]
Just seen your edit: Since the theme you are using isn‘t open source, i can‘t really have a look at it to investigate the problem. Sorry.
