### ISSUE TITLE
Checkbox doesn't hold its state when used on a custom post type

### ISSUE THREAD

**Issue by prostasia** [cyrillbolliger/conditional-featured-image#14]
This plugin works fine for pages and posts, but I have a custom post type on which I'm trying to use it, and it won't work. The checkbox appears, and I can select it, but when I update the page, the checkbox disappears and the featured image is still there. The custom post type doesn't use a special template, it just defaults to the regular post template. I created it using the plugin called CPT UI.

**Comment by richmahn** [comment]
@prostasia Did you figure out any more about this? Did you get it to work with your custom post type?

**Comment by prostasia** [comment]
I did not. I reported the bug and gave up.

**Comment by cyrillbolliger** [comment]
Sorry for not reacting @prostasia.

I'll try to find some spare minutes until next monday to reproduce and fix it. Could you guys tell me what theme you use (or if a plugin adds the custom post type, what theme and what plugins)?

**Comment by prostasia** [comment]
I used [Custom Post Type UI 1.7.4](https://wordpress.org/plugins/custom-post-type-ui/).

**Comment by cyrillbolliger** [comment]
@prostasia thanks. As a quick fix: Enable _Custom Fields_ in your custom post type, it should then work. I'll try to find a solution, that works out of the box, but I can't guarantee that it's possible...

![quick-fix](https://user-images.githubusercontent.com/12530490/103701470-5ee28100-4fa6-11eb-910c-3c45cb1c9556.png)

**Comment by prostasia** [comment]
Thanks, I can confirm that seems to work.

**Comment by cyrillbolliger** [comment]
Thanks for confirming. I found a way to enforce this programmatically, so you don't have to check the field manually anymore. The new version, 2.7.0, was just released here on github and in the wordpress' plugin repository.

Again, sorry for not reacting for such a long time, @prostasia!

@richmahn: I hope, this does also solve your problem...? If not, please open a new issue and provide some information about the theme and plugin you are using.
