### ISSUE TITLE
Featured image is also hidden in recent articles widget

### ISSUE THREAD

**Issue by etlel** [cyrillbolliger/conditional-featured-image#16]
I'm listing the latest articles in a widget inserted in the right sidebar of each article. The extension hides the image in the main contents area as expected, but also in the widget for the article that is open. The image is correctly displayed inside of the widget when consulting other articles.

**Comment by ReyanshKharga** [comment]
> I'm listing the latest articles in a widget inserted in the right sidebar of each article. The extension hides the image in the main contents area as expected, but also in the widget for the article that is open. The image is correctly displayed inside of the widget when consulting other articles.

I'm having the same issue. Did you come across another plugin that doesn't affect the widget for the article that is open?

**Comment by cyrillbolliger** [comment]
Hmmm, I've just tested it with the newsup theme. The _recent posts_ widget (on the lower right) does not show the featured image, regardless if I'm using the newsup theme or a default theme. The themes built in _latest_ block (upper right) however, shows the featured images as expected, despite one of them having the featured image hidden.

![image](https://user-images.githubusercontent.com/12530490/103204211-161c2f80-48f7-11eb-8945-4db189ec93c4.png)

So my question is: By default, there is no _latest articles_ widget, so **what widget do you use exactly and which plugin does it come with?**

**Comment by ReyanshKharga** [comment]
Please check the following post: https://worklifeandmoney.com/life/discernment/

If you scroll down there is a section called 'You Missed', The same post is listed there and has the featured image hidden.

**Comment by cyrillbolliger** [comment]
Thanks for pointing this out @etlel and @ReyanshKharga. I've just release version 2.5.1 which should fix this issue.

**Comment by ReyanshKharga** [comment]
Wow, I am amazed by the speed with which this issue was resolved. ❤️

**Comment by cyrillbolliger** [comment]
Thanks for the excellent rating @ReyanshKharga. I'm glad I could help.
