### ISSUE TITLE
Feature image reappears when post is updated

### ISSUE THREAD

**Issue by MiMoHo** [cyrillbolliger/conditional-featured-image#2]
When there is no feature image selected, but the box to only show the image on the overview page is checked, the feature image automatically selected from the article is only hidden in the post as long as it is not updated. Once the content of the post is updated, the box is not checked anymore and the automatically chosen first image appears as feature image on top and in the overview.
I'm using the latest version of Wordpress and the plugin in combination with "elementor".

**Comment by cyrillbolliger** [comment]
Thanks for pointing this out @MiMoHo. I've updated the plugin to support also the use of the elementor plugin. Just pull the latest update from the WordPress plugin repository.
