### ISSUE TITLE
Can we set the default setting of "Display featured image in post lists only, hide on singular views."

### ISSUE THREAD

**Issue by streich** [cyrillbolliger/conditional-featured-image#39]
Is there a way to change/set the default value of:

Display featured image in post lists only, hide on singular views.

I would like it always checked by default.

**Comment by cyrillbolliger** [comment]
It doesn't matter where you place the snipped, as long as it is directly in the `functions.php` and not inside a function. You may want to read https://ithemes.com/blog/wordpress-functions-php-file-explained/
