### ISSUE TITLE
Doesn't work when post list is shown on a page

### ISSUE THREAD

**Issue by jdmansour** [cyrillbolliger/conditional-featured-image#43]
Hi, I'm using the twenty twenty-three theme. Instead of using the site editor to edit the front page, I created a new "page" and put the recent post list there (with the loop block, just copied the blocks from the default front page). The page looks the same, the benefit is that it is now version controlled. Here is what it looks like (sorry for the German):

![grafik](https://user-images.githubusercontent.com/110078/232285153-2ab71a10-7a95-4f5b-97df-01aa4b5b74b7.png)

However, this plugin doesn't recognize that it is in a post list, and hides the featured image in the list, too. Is there any way to get it to recognize the situation and to show the image there?

**Comment by cyrillbolliger** [comment]
Thanks for reporting. I've just fixed the issue and released an update. It should be available in WordPress' plugin repository in a few minutes.

**Comment by jdmansour** [comment]
Wow, thanks for the quick fix, I'll give it a try!

**Comment by cyrillbolliger** [comment]
Thanks a lot for the feedback and the experimental fix. Are you sure you've tested the latest version? Your fix doesn't seem to contain the relevant commit 6f03d4910d9b837bf9fb94dd604594ef32a841c1...

I'd prefer to explicitly check for the query block than changing the `is_singular()` and `is_main_query()` checks, as this introduces less risk of breaking existing installations (you never know what plugins people use and what magic they do).

**Comment by jdmansour** [comment]
One addition, this is the place where the query block performs the loop:
https://github.com/WordPress/WordPress/blob/master/wp-includes/blocks/post-template.php#L78

It does call `$query->the_post()` on each post. I thought this would populate all the global variables. But still, `is_main_query()` returns true and `$query->is_main_query()` returns false (which is what is needed as far as I understand).

**Comment by cyrillbolliger** [comment]
Thanks a lot for those valuable details. I'll investigate in detail as soon as I've got some time. It may take until the weekend...

**Comment by cyrillbolliger** [comment]
Thank you very much for your patience and for the exceptionally well error description. This was very helpful to reproduce the issue and (hopefully) finally fix it.

Would you like to test it, bevor I publish the release? https://github.com/cyrillbolliger/conditional-featured-image/tree/dev

I permitted myself to cherry-pick your fix and adapting it. I hope this is ok for you? I'd be more than happy to credit your contribution also on WordPress. If you agree so, please let me know your handle from [wordpress](https://profiles.wordpress.org/) and I'll add you to the contributors list.
