### ISSUE TITLE
Not displaying archive thumbnails

### ISSUE THREAD

**Issue by skelleyh** [cyrillbolliger/conditional-featured-image#5]
Hi!
The Featured Image is suppressed appropriately on single post pages; however, the suppressed Featured Image doesn't display on the doman.com/blog aggregate page. I want it to show there, just not on the actual single post page. My understanding of this plug-in is that the Featured Image will still display on aggregate pages and social media link posts, just not on the actual page. Is that correct, and if so, what is required for it to work correctly?
Thank you.

**Comment by cyrillbolliger** [comment]
Hi Skelleyh
Thanks for using this plugin. Yes, the plugin should exactly do, what you described. Here is an [example](http://bolliger.tech/): The Featured Image is visible on the archive page but hidden in the singular view. However, it may depend on how your theme is built. If domain.com/blog returns true on either `is_page()` or `is_single()`, the image will also be hidden.
So could you please investigate, what domain.com/blog returns for this two functions? In case these are both false, send me some further information on what theme and plugin you use, so I can have a look at it?
Cheers,
Cyrill

**Comment by skelleyh** [comment]
Thanks for your note!
I don't know how to validate the two things you noted, though I'm using
1.4.0 of the plugin, and I am using the Divi theme 3.23.3.

I hope you are well.

**Comment by cyrillbolliger** [comment]
The Divi-Theme is so far away from a standard WordPress theme – it works really different. Therefore it is not supported.
